//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Foriba.OE.CLIENT.serviceSmm {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://foriba.com/eSmm/")]
    public partial class ProcessingFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codeField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://foriba.com/eSmm/")]
    public partial class sendDocumentResponseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string uUIDField;
        
        private string idField;
        
        private string custDocIDField;
        
        private string typeField;
        
        private string docTypeField;
        
        private byte[] docDataField;
        
        private byte[] viewDataField;
        
        private ParametersType[] parametersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UUID {
            get {
                return this.uUIDField;
            }
            set {
                this.uUIDField = value;
                this.RaisePropertyChanged("UUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CustDocID {
            get {
                return this.custDocIDField;
            }
            set {
                this.custDocIDField = value;
                this.RaisePropertyChanged("CustDocID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string DocType {
            get {
                return this.docTypeField;
            }
            set {
                this.docTypeField = value;
                this.RaisePropertyChanged("DocType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=5)]
        public byte[] DocData {
            get {
                return this.docDataField;
            }
            set {
                this.docDataField = value;
                this.RaisePropertyChanged("DocData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=6)]
        public byte[] ViewData {
            get {
                return this.viewDataField;
            }
            set {
                this.viewDataField = value;
                this.RaisePropertyChanged("ViewData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Parameters", Order=7)]
        public ParametersType[] Parameters {
            get {
                return this.parametersField;
            }
            set {
                this.parametersField = value;
                this.RaisePropertyChanged("Parameters");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://foriba.com/eSmm/")]
    public partial class ParametersType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://foriba.com/eSmm/")]
    public partial class sendDocumentRequestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string uUIDField;
        
        private string typeField;
        
        private string docTypeField;
        
        private byte[] docDataField;
        
        private string viewTypeField;
        
        private ParametersType[] parametersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UUID {
            get {
                return this.uUIDField;
            }
            set {
                this.uUIDField = value;
                this.RaisePropertyChanged("UUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string DocType {
            get {
                return this.docTypeField;
            }
            set {
                this.docTypeField = value;
                this.RaisePropertyChanged("DocType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=3)]
        public byte[] DocData {
            get {
                return this.docDataField;
            }
            set {
                this.docDataField = value;
                this.RaisePropertyChanged("DocData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ViewType {
            get {
                return this.viewTypeField;
            }
            set {
                this.viewTypeField = value;
                this.RaisePropertyChanged("ViewType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Parameters", Order=5)]
        public ParametersType[] Parameters {
            get {
                return this.parametersField;
            }
            set {
                this.parametersField = value;
                this.RaisePropertyChanged("Parameters");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://foriba.com/eSmm/", ConfigurationName="serviceSmm.ForibaESmmServicesPort")]
    public interface ForibaESmmServicesPort {
        
        // CODEGEN: Generating message contract since the operation sendDocument is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="sendDocument", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Foriba.OE.CLIENT.serviceSmm.ProcessingFault), Action="sendDocument", Name="ProcessingFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Foriba.OE.CLIENT.serviceSmm.sendDocumentResponse sendDocument(Foriba.OE.CLIENT.serviceSmm.sendDocumentRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="sendDocument", ReplyAction="*")]
        System.Threading.Tasks.Task<Foriba.OE.CLIENT.serviceSmm.sendDocumentResponse> sendDocumentAsync(Foriba.OE.CLIENT.serviceSmm.sendDocumentRequest1 request);
        
        // CODEGEN: Generating message contract since the operation getDocument is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="getDocument", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Foriba.OE.CLIENT.serviceSmm.ProcessingFault), Action="getDocument", Name="ProcessingFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Foriba.OE.CLIENT.serviceSmm.getDocumentResponse getDocument(Foriba.OE.CLIENT.serviceSmm.getDocumentRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getDocument", ReplyAction="*")]
        System.Threading.Tasks.Task<Foriba.OE.CLIENT.serviceSmm.getDocumentResponse> getDocumentAsync(Foriba.OE.CLIENT.serviceSmm.getDocumentRequest1 request);
        
        // CODEGEN: Generating message contract since the operation getReportList is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="getReportList", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Foriba.OE.CLIENT.serviceSmm.ProcessingFault), Action="getReportList", Name="ProcessingFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Foriba.OE.CLIENT.serviceSmm.getReportListResponse getReportList(Foriba.OE.CLIENT.serviceSmm.getReportListRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getReportList", ReplyAction="*")]
        System.Threading.Tasks.Task<Foriba.OE.CLIENT.serviceSmm.getReportListResponse> getReportListAsync(Foriba.OE.CLIENT.serviceSmm.getReportListRequest1 request);
        
        // CODEGEN: Generating message contract since the operation getReportData is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="getReportData", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Foriba.OE.CLIENT.serviceSmm.ProcessingFault), Action="getReportData", Name="ProcessingFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Foriba.OE.CLIENT.serviceSmm.getReportDataResponse getReportData(Foriba.OE.CLIENT.serviceSmm.getReportDataRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getReportData", ReplyAction="*")]
        System.Threading.Tasks.Task<Foriba.OE.CLIENT.serviceSmm.getReportDataResponse> getReportDataAsync(Foriba.OE.CLIENT.serviceSmm.getReportDataRequest1 request);
        
        // CODEGEN: Generating message contract since the operation cancelDocument is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="cancelDocument", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Foriba.OE.CLIENT.serviceSmm.ProcessingFault), Action="cancelDocument", Name="ProcessingFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Foriba.OE.CLIENT.serviceSmm.cancelDocumentResponse cancelDocument(Foriba.OE.CLIENT.serviceSmm.cancelDocumentRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="cancelDocument", ReplyAction="*")]
        System.Threading.Tasks.Task<Foriba.OE.CLIENT.serviceSmm.cancelDocumentResponse> cancelDocumentAsync(Foriba.OE.CLIENT.serviceSmm.cancelDocumentRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://foriba.com/eSmm/")]
    public partial class sendDocumentRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string vKN_TCKNField;
        
        private string branchField;
        
        private sendDocumentRequestType[] sendDocDetailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string VKN_TCKN {
            get {
                return this.vKN_TCKNField;
            }
            set {
                this.vKN_TCKNField = value;
                this.RaisePropertyChanged("VKN_TCKN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Branch {
            get {
                return this.branchField;
            }
            set {
                this.branchField = value;
                this.RaisePropertyChanged("Branch");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SendDocDetails", Order=2)]
        public sendDocumentRequestType[] SendDocDetails {
            get {
                return this.sendDocDetailsField;
            }
            set {
                this.sendDocDetailsField = value;
                this.RaisePropertyChanged("SendDocDetails");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendDocumentRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://foriba.com/eSmm/", Order=0)]
        public Foriba.OE.CLIENT.serviceSmm.sendDocumentRequest sendDocumentRequest;
        
        public sendDocumentRequest1() {
        }
        
        public sendDocumentRequest1(Foriba.OE.CLIENT.serviceSmm.sendDocumentRequest sendDocumentRequest) {
            this.sendDocumentRequest = sendDocumentRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendDocumentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendDocumentResponse", Namespace="http://foriba.com/eSmm/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("SendDocumentResponse", IsNullable=false)]
        public Foriba.OE.CLIENT.serviceSmm.sendDocumentResponseType[] sendDocumentResponse1;
        
        public sendDocumentResponse() {
        }
        
        public sendDocumentResponse(Foriba.OE.CLIENT.serviceSmm.sendDocumentResponseType[] sendDocumentResponse1) {
            this.sendDocumentResponse1 = sendDocumentResponse1;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://foriba.com/eSmm/")]
    public partial class getDocumentRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string vKN_TCKNField;
        
        private getDocumentRequestType[] getDocDetailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string VKN_TCKN {
            get {
                return this.vKN_TCKNField;
            }
            set {
                this.vKN_TCKNField = value;
                this.RaisePropertyChanged("VKN_TCKN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("GetDocDetails", Order=1)]
        public getDocumentRequestType[] GetDocDetails {
            get {
                return this.getDocDetailsField;
            }
            set {
                this.getDocDetailsField = value;
                this.RaisePropertyChanged("GetDocDetails");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://foriba.com/eSmm/")]
    public partial class getDocumentRequestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string uUIDField;
        
        private string idField;
        
        private string custDocIDField;
        
        private string typeField;
        
        private string docTypeField;
        
        private string viewTypeField;
        
        private ParametersType[] parametersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UUID {
            get {
                return this.uUIDField;
            }
            set {
                this.uUIDField = value;
                this.RaisePropertyChanged("UUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CustDocID {
            get {
                return this.custDocIDField;
            }
            set {
                this.custDocIDField = value;
                this.RaisePropertyChanged("CustDocID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string DocType {
            get {
                return this.docTypeField;
            }
            set {
                this.docTypeField = value;
                this.RaisePropertyChanged("DocType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ViewType {
            get {
                return this.viewTypeField;
            }
            set {
                this.viewTypeField = value;
                this.RaisePropertyChanged("ViewType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Parameters", Order=6)]
        public ParametersType[] Parameters {
            get {
                return this.parametersField;
            }
            set {
                this.parametersField = value;
                this.RaisePropertyChanged("Parameters");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://foriba.com/eSmm/")]
    public partial class getDocumentResponseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string uUIDField;
        
        private string idField;
        
        private string custDocIDField;
        
        private string typeField;
        
        private string docTypeField;
        
        private string viewTypeField;
        
        private byte[] docDataField;
        
        private int resultField;
        
        private string resultDescriptionField;
        
        private ParametersType[] parametersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UUID {
            get {
                return this.uUIDField;
            }
            set {
                this.uUIDField = value;
                this.RaisePropertyChanged("UUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CustDocID {
            get {
                return this.custDocIDField;
            }
            set {
                this.custDocIDField = value;
                this.RaisePropertyChanged("CustDocID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string DocType {
            get {
                return this.docTypeField;
            }
            set {
                this.docTypeField = value;
                this.RaisePropertyChanged("DocType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ViewType {
            get {
                return this.viewTypeField;
            }
            set {
                this.viewTypeField = value;
                this.RaisePropertyChanged("ViewType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=6)]
        public byte[] DocData {
            get {
                return this.docDataField;
            }
            set {
                this.docDataField = value;
                this.RaisePropertyChanged("DocData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("Result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string ResultDescription {
            get {
                return this.resultDescriptionField;
            }
            set {
                this.resultDescriptionField = value;
                this.RaisePropertyChanged("ResultDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Parameters", Order=9)]
        public ParametersType[] Parameters {
            get {
                return this.parametersField;
            }
            set {
                this.parametersField = value;
                this.RaisePropertyChanged("Parameters");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDocumentRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://foriba.com/eSmm/", Order=0)]
        public Foriba.OE.CLIENT.serviceSmm.getDocumentRequest getDocumentRequest;
        
        public getDocumentRequest1() {
        }
        
        public getDocumentRequest1(Foriba.OE.CLIENT.serviceSmm.getDocumentRequest getDocumentRequest) {
            this.getDocumentRequest = getDocumentRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDocumentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDocumentResponse", Namespace="http://foriba.com/eSmm/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("getDocumentResponse", IsNullable=false)]
        public Foriba.OE.CLIENT.serviceSmm.getDocumentResponseType[] getDocumentResponse1;
        
        public getDocumentResponse() {
        }
        
        public getDocumentResponse(Foriba.OE.CLIENT.serviceSmm.getDocumentResponseType[] getDocumentResponse1) {
            this.getDocumentResponse1 = getDocumentResponse1;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://foriba.com/eSmm/")]
    public partial class getReportListRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string vKN_TCKNField;
        
        private string typeField;
        
        private string docTypeField;
        
        private int yearField;
        
        private int monthField;
        
        private ParametersType[] parametersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string VKN_TCKN {
            get {
                return this.vKN_TCKNField;
            }
            set {
                this.vKN_TCKNField = value;
                this.RaisePropertyChanged("VKN_TCKN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string DocType {
            get {
                return this.docTypeField;
            }
            set {
                this.docTypeField = value;
                this.RaisePropertyChanged("DocType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
                this.RaisePropertyChanged("Year");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int Month {
            get {
                return this.monthField;
            }
            set {
                this.monthField = value;
                this.RaisePropertyChanged("Month");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Parameters", Order=5)]
        public ParametersType[] Parameters {
            get {
                return this.parametersField;
            }
            set {
                this.parametersField = value;
                this.RaisePropertyChanged("Parameters");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://foriba.com/eSmm/")]
    public partial class getReportListResponseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string uUIDField;
        
        private string vKN_TCKNField;
        
        private string typeField;
        
        private string docTypeField;
        
        private int yearField;
        
        private int monthField;
        
        private System.DateTime sectionStartDateField;
        
        private System.DateTime sectionEndDateField;
        
        private int partNumberField;
        
        private int documentCountField;
        
        private decimal documentTotalAmountField;
        
        private int canceledDocumentCountField;
        
        private decimal canceledDocumentTotalAmountField;
        
        private int gIBStatusCodeField;
        
        private string gIBStatusDescField;
        
        private ParametersType[] parametersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UUID {
            get {
                return this.uUIDField;
            }
            set {
                this.uUIDField = value;
                this.RaisePropertyChanged("UUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string VKN_TCKN {
            get {
                return this.vKN_TCKNField;
            }
            set {
                this.vKN_TCKNField = value;
                this.RaisePropertyChanged("VKN_TCKN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DocType {
            get {
                return this.docTypeField;
            }
            set {
                this.docTypeField = value;
                this.RaisePropertyChanged("DocType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int Year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
                this.RaisePropertyChanged("Year");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int Month {
            get {
                return this.monthField;
            }
            set {
                this.monthField = value;
                this.RaisePropertyChanged("Month");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=6)]
        public System.DateTime SectionStartDate {
            get {
                return this.sectionStartDateField;
            }
            set {
                this.sectionStartDateField = value;
                this.RaisePropertyChanged("SectionStartDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=7)]
        public System.DateTime SectionEndDate {
            get {
                return this.sectionEndDateField;
            }
            set {
                this.sectionEndDateField = value;
                this.RaisePropertyChanged("SectionEndDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int PartNumber {
            get {
                return this.partNumberField;
            }
            set {
                this.partNumberField = value;
                this.RaisePropertyChanged("PartNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int DocumentCount {
            get {
                return this.documentCountField;
            }
            set {
                this.documentCountField = value;
                this.RaisePropertyChanged("DocumentCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public decimal DocumentTotalAmount {
            get {
                return this.documentTotalAmountField;
            }
            set {
                this.documentTotalAmountField = value;
                this.RaisePropertyChanged("DocumentTotalAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int CanceledDocumentCount {
            get {
                return this.canceledDocumentCountField;
            }
            set {
                this.canceledDocumentCountField = value;
                this.RaisePropertyChanged("CanceledDocumentCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public decimal CanceledDocumentTotalAmount {
            get {
                return this.canceledDocumentTotalAmountField;
            }
            set {
                this.canceledDocumentTotalAmountField = value;
                this.RaisePropertyChanged("CanceledDocumentTotalAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public int GIBStatusCode {
            get {
                return this.gIBStatusCodeField;
            }
            set {
                this.gIBStatusCodeField = value;
                this.RaisePropertyChanged("GIBStatusCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string GIBStatusDesc {
            get {
                return this.gIBStatusDescField;
            }
            set {
                this.gIBStatusDescField = value;
                this.RaisePropertyChanged("GIBStatusDesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Parameters", Order=15)]
        public ParametersType[] Parameters {
            get {
                return this.parametersField;
            }
            set {
                this.parametersField = value;
                this.RaisePropertyChanged("Parameters");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getReportListRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://foriba.com/eSmm/", Order=0)]
        public Foriba.OE.CLIENT.serviceSmm.getReportListRequest getReportListRequest;
        
        public getReportListRequest1() {
        }
        
        public getReportListRequest1(Foriba.OE.CLIENT.serviceSmm.getReportListRequest getReportListRequest) {
            this.getReportListRequest = getReportListRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getReportListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getReportListResponse", Namespace="http://foriba.com/eSmm/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("getReportList", IsNullable=false)]
        public Foriba.OE.CLIENT.serviceSmm.getReportListResponseType[] getReportListResponse1;
        
        public getReportListResponse() {
        }
        
        public getReportListResponse(Foriba.OE.CLIENT.serviceSmm.getReportListResponseType[] getReportListResponse1) {
            this.getReportListResponse1 = getReportListResponse1;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://foriba.com/eSmm/")]
    public partial class getReportDataRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string vKN_TCKNField;
        
        private getDocumentReportDataRequestType[] getDocReportDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string VKN_TCKN {
            get {
                return this.vKN_TCKNField;
            }
            set {
                this.vKN_TCKNField = value;
                this.RaisePropertyChanged("VKN_TCKN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("GetDocReportData", Order=1)]
        public getDocumentReportDataRequestType[] GetDocReportData {
            get {
                return this.getDocReportDataField;
            }
            set {
                this.getDocReportDataField = value;
                this.RaisePropertyChanged("GetDocReportData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://foriba.com/eSmm/")]
    public partial class getDocumentReportDataRequestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string uUIDField;
        
        private string typeField;
        
        private string docTypeField;
        
        private ParametersType[] parametersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UUID {
            get {
                return this.uUIDField;
            }
            set {
                this.uUIDField = value;
                this.RaisePropertyChanged("UUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string DocType {
            get {
                return this.docTypeField;
            }
            set {
                this.docTypeField = value;
                this.RaisePropertyChanged("DocType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Parameters", Order=3)]
        public ParametersType[] Parameters {
            get {
                return this.parametersField;
            }
            set {
                this.parametersField = value;
                this.RaisePropertyChanged("Parameters");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://foriba.com/eSmm/")]
    public partial class getDocumentReportDataResponseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string uUIDField;
        
        private string typeField;
        
        private string docTypeField;
        
        private byte[] docDataField;
        
        private ParametersType[] parametersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UUID {
            get {
                return this.uUIDField;
            }
            set {
                this.uUIDField = value;
                this.RaisePropertyChanged("UUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string DocType {
            get {
                return this.docTypeField;
            }
            set {
                this.docTypeField = value;
                this.RaisePropertyChanged("DocType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=3)]
        public byte[] DocData {
            get {
                return this.docDataField;
            }
            set {
                this.docDataField = value;
                this.RaisePropertyChanged("DocData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Parameters", Order=4)]
        public ParametersType[] Parameters {
            get {
                return this.parametersField;
            }
            set {
                this.parametersField = value;
                this.RaisePropertyChanged("Parameters");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getReportDataRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://foriba.com/eSmm/", Order=0)]
        public Foriba.OE.CLIENT.serviceSmm.getReportDataRequest getReportDataRequest;
        
        public getReportDataRequest1() {
        }
        
        public getReportDataRequest1(Foriba.OE.CLIENT.serviceSmm.getReportDataRequest getReportDataRequest) {
            this.getReportDataRequest = getReportDataRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getReportDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getReportDataResponse", Namespace="http://foriba.com/eSmm/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("getDocReportData", IsNullable=false)]
        public Foriba.OE.CLIENT.serviceSmm.getDocumentReportDataResponseType[] getReportDataResponse1;
        
        public getReportDataResponse() {
        }
        
        public getReportDataResponse(Foriba.OE.CLIENT.serviceSmm.getDocumentReportDataResponseType[] getReportDataResponse1) {
            this.getReportDataResponse1 = getReportDataResponse1;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://foriba.com/eSmm/")]
    public partial class cancelDocumentRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string vKN_TCKNField;
        
        private string branchField;
        
        private cancelDocumentRequestType[] cancelDocDetailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string VKN_TCKN {
            get {
                return this.vKN_TCKNField;
            }
            set {
                this.vKN_TCKNField = value;
                this.RaisePropertyChanged("VKN_TCKN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Branch {
            get {
                return this.branchField;
            }
            set {
                this.branchField = value;
                this.RaisePropertyChanged("Branch");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CancelDocDetails", Order=2)]
        public cancelDocumentRequestType[] CancelDocDetails {
            get {
                return this.cancelDocDetailsField;
            }
            set {
                this.cancelDocDetailsField = value;
                this.RaisePropertyChanged("CancelDocDetails");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://foriba.com/eSmm/")]
    public partial class cancelDocumentRequestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string custDocIDField;
        
        private string typeField;
        
        private string docTypeField;
        
        private decimal totalAmountField;
        
        private System.DateTime cancelDateField;
        
        private ParametersType[] parametersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CustDocID {
            get {
                return this.custDocIDField;
            }
            set {
                this.custDocIDField = value;
                this.RaisePropertyChanged("CustDocID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DocType {
            get {
                return this.docTypeField;
            }
            set {
                this.docTypeField = value;
                this.RaisePropertyChanged("DocType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public decimal TotalAmount {
            get {
                return this.totalAmountField;
            }
            set {
                this.totalAmountField = value;
                this.RaisePropertyChanged("TotalAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=5)]
        public System.DateTime CancelDate {
            get {
                return this.cancelDateField;
            }
            set {
                this.cancelDateField = value;
                this.RaisePropertyChanged("CancelDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Parameters", Order=6)]
        public ParametersType[] Parameters {
            get {
                return this.parametersField;
            }
            set {
                this.parametersField = value;
                this.RaisePropertyChanged("Parameters");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://foriba.com/eSmm/")]
    public partial class cancelDocumentResponseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string custDocIDField;
        
        private string typeField;
        
        private string docTypeField;
        
        private int resultField;
        
        private string resultDescriptionField;
        
        private ParametersType[] parametersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CustDocID {
            get {
                return this.custDocIDField;
            }
            set {
                this.custDocIDField = value;
                this.RaisePropertyChanged("CustDocID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DocType {
            get {
                return this.docTypeField;
            }
            set {
                this.docTypeField = value;
                this.RaisePropertyChanged("DocType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("Result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ResultDescription {
            get {
                return this.resultDescriptionField;
            }
            set {
                this.resultDescriptionField = value;
                this.RaisePropertyChanged("ResultDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Parameters", Order=6)]
        public ParametersType[] Parameters {
            get {
                return this.parametersField;
            }
            set {
                this.parametersField = value;
                this.RaisePropertyChanged("Parameters");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cancelDocumentRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://foriba.com/eSmm/", Order=0)]
        public Foriba.OE.CLIENT.serviceSmm.cancelDocumentRequest cancelDocumentRequest;
        
        public cancelDocumentRequest1() {
        }
        
        public cancelDocumentRequest1(Foriba.OE.CLIENT.serviceSmm.cancelDocumentRequest cancelDocumentRequest) {
            this.cancelDocumentRequest = cancelDocumentRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cancelDocumentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="cancelDocumentResponse", Namespace="http://foriba.com/eSmm/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("cancelDocumentResponse", IsNullable=false)]
        public Foriba.OE.CLIENT.serviceSmm.cancelDocumentResponseType[] cancelDocumentResponse1;
        
        public cancelDocumentResponse() {
        }
        
        public cancelDocumentResponse(Foriba.OE.CLIENT.serviceSmm.cancelDocumentResponseType[] cancelDocumentResponse1) {
            this.cancelDocumentResponse1 = cancelDocumentResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ForibaESmmServicesPortChannel : Foriba.OE.CLIENT.serviceSmm.ForibaESmmServicesPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ForibaESmmServicesPortClient : System.ServiceModel.ClientBase<Foriba.OE.CLIENT.serviceSmm.ForibaESmmServicesPort>, Foriba.OE.CLIENT.serviceSmm.ForibaESmmServicesPort {
        
        public ForibaESmmServicesPortClient() {
        }
        
        public ForibaESmmServicesPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ForibaESmmServicesPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ForibaESmmServicesPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ForibaESmmServicesPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Foriba.OE.CLIENT.serviceSmm.sendDocumentResponse Foriba.OE.CLIENT.serviceSmm.ForibaESmmServicesPort.sendDocument(Foriba.OE.CLIENT.serviceSmm.sendDocumentRequest1 request) {
            return base.Channel.sendDocument(request);
        }
        
        public Foriba.OE.CLIENT.serviceSmm.sendDocumentResponseType[] sendDocument(Foriba.OE.CLIENT.serviceSmm.sendDocumentRequest sendDocumentRequest) {
            Foriba.OE.CLIENT.serviceSmm.sendDocumentRequest1 inValue = new Foriba.OE.CLIENT.serviceSmm.sendDocumentRequest1();
            inValue.sendDocumentRequest = sendDocumentRequest;
            Foriba.OE.CLIENT.serviceSmm.sendDocumentResponse retVal = ((Foriba.OE.CLIENT.serviceSmm.ForibaESmmServicesPort)(this)).sendDocument(inValue);
            return retVal.sendDocumentResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Foriba.OE.CLIENT.serviceSmm.sendDocumentResponse> Foriba.OE.CLIENT.serviceSmm.ForibaESmmServicesPort.sendDocumentAsync(Foriba.OE.CLIENT.serviceSmm.sendDocumentRequest1 request) {
            return base.Channel.sendDocumentAsync(request);
        }
        
        public System.Threading.Tasks.Task<Foriba.OE.CLIENT.serviceSmm.sendDocumentResponse> sendDocumentAsync(Foriba.OE.CLIENT.serviceSmm.sendDocumentRequest sendDocumentRequest) {
            Foriba.OE.CLIENT.serviceSmm.sendDocumentRequest1 inValue = new Foriba.OE.CLIENT.serviceSmm.sendDocumentRequest1();
            inValue.sendDocumentRequest = sendDocumentRequest;
            return ((Foriba.OE.CLIENT.serviceSmm.ForibaESmmServicesPort)(this)).sendDocumentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Foriba.OE.CLIENT.serviceSmm.getDocumentResponse Foriba.OE.CLIENT.serviceSmm.ForibaESmmServicesPort.getDocument(Foriba.OE.CLIENT.serviceSmm.getDocumentRequest1 request) {
            return base.Channel.getDocument(request);
        }
        
        public Foriba.OE.CLIENT.serviceSmm.getDocumentResponseType[] getDocument(Foriba.OE.CLIENT.serviceSmm.getDocumentRequest getDocumentRequest) {
            Foriba.OE.CLIENT.serviceSmm.getDocumentRequest1 inValue = new Foriba.OE.CLIENT.serviceSmm.getDocumentRequest1();
            inValue.getDocumentRequest = getDocumentRequest;
            Foriba.OE.CLIENT.serviceSmm.getDocumentResponse retVal = ((Foriba.OE.CLIENT.serviceSmm.ForibaESmmServicesPort)(this)).getDocument(inValue);
            return retVal.getDocumentResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Foriba.OE.CLIENT.serviceSmm.getDocumentResponse> Foriba.OE.CLIENT.serviceSmm.ForibaESmmServicesPort.getDocumentAsync(Foriba.OE.CLIENT.serviceSmm.getDocumentRequest1 request) {
            return base.Channel.getDocumentAsync(request);
        }
        
        public System.Threading.Tasks.Task<Foriba.OE.CLIENT.serviceSmm.getDocumentResponse> getDocumentAsync(Foriba.OE.CLIENT.serviceSmm.getDocumentRequest getDocumentRequest) {
            Foriba.OE.CLIENT.serviceSmm.getDocumentRequest1 inValue = new Foriba.OE.CLIENT.serviceSmm.getDocumentRequest1();
            inValue.getDocumentRequest = getDocumentRequest;
            return ((Foriba.OE.CLIENT.serviceSmm.ForibaESmmServicesPort)(this)).getDocumentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Foriba.OE.CLIENT.serviceSmm.getReportListResponse Foriba.OE.CLIENT.serviceSmm.ForibaESmmServicesPort.getReportList(Foriba.OE.CLIENT.serviceSmm.getReportListRequest1 request) {
            return base.Channel.getReportList(request);
        }
        
        public Foriba.OE.CLIENT.serviceSmm.getReportListResponseType[] getReportList(Foriba.OE.CLIENT.serviceSmm.getReportListRequest getReportListRequest) {
            Foriba.OE.CLIENT.serviceSmm.getReportListRequest1 inValue = new Foriba.OE.CLIENT.serviceSmm.getReportListRequest1();
            inValue.getReportListRequest = getReportListRequest;
            Foriba.OE.CLIENT.serviceSmm.getReportListResponse retVal = ((Foriba.OE.CLIENT.serviceSmm.ForibaESmmServicesPort)(this)).getReportList(inValue);
            return retVal.getReportListResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Foriba.OE.CLIENT.serviceSmm.getReportListResponse> Foriba.OE.CLIENT.serviceSmm.ForibaESmmServicesPort.getReportListAsync(Foriba.OE.CLIENT.serviceSmm.getReportListRequest1 request) {
            return base.Channel.getReportListAsync(request);
        }
        
        public System.Threading.Tasks.Task<Foriba.OE.CLIENT.serviceSmm.getReportListResponse> getReportListAsync(Foriba.OE.CLIENT.serviceSmm.getReportListRequest getReportListRequest) {
            Foriba.OE.CLIENT.serviceSmm.getReportListRequest1 inValue = new Foriba.OE.CLIENT.serviceSmm.getReportListRequest1();
            inValue.getReportListRequest = getReportListRequest;
            return ((Foriba.OE.CLIENT.serviceSmm.ForibaESmmServicesPort)(this)).getReportListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Foriba.OE.CLIENT.serviceSmm.getReportDataResponse Foriba.OE.CLIENT.serviceSmm.ForibaESmmServicesPort.getReportData(Foriba.OE.CLIENT.serviceSmm.getReportDataRequest1 request) {
            return base.Channel.getReportData(request);
        }
        
        public Foriba.OE.CLIENT.serviceSmm.getDocumentReportDataResponseType[] getReportData(Foriba.OE.CLIENT.serviceSmm.getReportDataRequest getReportDataRequest) {
            Foriba.OE.CLIENT.serviceSmm.getReportDataRequest1 inValue = new Foriba.OE.CLIENT.serviceSmm.getReportDataRequest1();
            inValue.getReportDataRequest = getReportDataRequest;
            Foriba.OE.CLIENT.serviceSmm.getReportDataResponse retVal = ((Foriba.OE.CLIENT.serviceSmm.ForibaESmmServicesPort)(this)).getReportData(inValue);
            return retVal.getReportDataResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Foriba.OE.CLIENT.serviceSmm.getReportDataResponse> Foriba.OE.CLIENT.serviceSmm.ForibaESmmServicesPort.getReportDataAsync(Foriba.OE.CLIENT.serviceSmm.getReportDataRequest1 request) {
            return base.Channel.getReportDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<Foriba.OE.CLIENT.serviceSmm.getReportDataResponse> getReportDataAsync(Foriba.OE.CLIENT.serviceSmm.getReportDataRequest getReportDataRequest) {
            Foriba.OE.CLIENT.serviceSmm.getReportDataRequest1 inValue = new Foriba.OE.CLIENT.serviceSmm.getReportDataRequest1();
            inValue.getReportDataRequest = getReportDataRequest;
            return ((Foriba.OE.CLIENT.serviceSmm.ForibaESmmServicesPort)(this)).getReportDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Foriba.OE.CLIENT.serviceSmm.cancelDocumentResponse Foriba.OE.CLIENT.serviceSmm.ForibaESmmServicesPort.cancelDocument(Foriba.OE.CLIENT.serviceSmm.cancelDocumentRequest1 request) {
            return base.Channel.cancelDocument(request);
        }
        
        public Foriba.OE.CLIENT.serviceSmm.cancelDocumentResponseType[] cancelDocument(Foriba.OE.CLIENT.serviceSmm.cancelDocumentRequest cancelDocumentRequest) {
            Foriba.OE.CLIENT.serviceSmm.cancelDocumentRequest1 inValue = new Foriba.OE.CLIENT.serviceSmm.cancelDocumentRequest1();
            inValue.cancelDocumentRequest = cancelDocumentRequest;
            Foriba.OE.CLIENT.serviceSmm.cancelDocumentResponse retVal = ((Foriba.OE.CLIENT.serviceSmm.ForibaESmmServicesPort)(this)).cancelDocument(inValue);
            return retVal.cancelDocumentResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Foriba.OE.CLIENT.serviceSmm.cancelDocumentResponse> Foriba.OE.CLIENT.serviceSmm.ForibaESmmServicesPort.cancelDocumentAsync(Foriba.OE.CLIENT.serviceSmm.cancelDocumentRequest1 request) {
            return base.Channel.cancelDocumentAsync(request);
        }
        
        public System.Threading.Tasks.Task<Foriba.OE.CLIENT.serviceSmm.cancelDocumentResponse> cancelDocumentAsync(Foriba.OE.CLIENT.serviceSmm.cancelDocumentRequest cancelDocumentRequest) {
            Foriba.OE.CLIENT.serviceSmm.cancelDocumentRequest1 inValue = new Foriba.OE.CLIENT.serviceSmm.cancelDocumentRequest1();
            inValue.cancelDocumentRequest = cancelDocumentRequest;
            return ((Foriba.OE.CLIENT.serviceSmm.ForibaESmmServicesPort)(this)).cancelDocumentAsync(inValue);
        }
    }
}
