//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Foriba.OE.CLIENT.serviceInvoicee {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http:/fitcons.com/eInvoice/")]
    public partial class ProcessingFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codeField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http:/fitcons.com/eInvoice/")]
    public partial class SendUBLResponseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string envUUIDField;
        
        private string uUIDField;
        
        private string idField;
        
        private string custInvIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string EnvUUID {
            get {
                return this.envUUIDField;
            }
            set {
                this.envUUIDField = value;
                this.RaisePropertyChanged("EnvUUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string UUID {
            get {
                return this.uUIDField;
            }
            set {
                this.uUIDField = value;
                this.RaisePropertyChanged("UUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string CustInvID {
            get {
                return this.custInvIDField;
            }
            set {
                this.custInvIDField = value;
                this.RaisePropertyChanged("CustInvID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http:/fitcons.com/eInvoice/", ConfigurationName="serviceInvoicee.ClientEInvoiceServicesPort")]
    public interface ClientEInvoiceServicesPort {
        
        // CODEGEN: Generating message contract since the operation sendUBL is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="sendUBL", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Foriba.OE.CLIENT.serviceInvoicee.ProcessingFault), Action="sendUBL", Name="ProcessingFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Foriba.OE.CLIENT.serviceInvoicee.sendUBLResponse sendUBL(Foriba.OE.CLIENT.serviceInvoicee.sendUBLRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="sendUBL", ReplyAction="*")]
        System.Threading.Tasks.Task<Foriba.OE.CLIENT.serviceInvoicee.sendUBLResponse> sendUBLAsync(Foriba.OE.CLIENT.serviceInvoicee.sendUBLRequest1 request);
        
        // CODEGEN: Generating message contract since the operation getUBLList is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="getUBLList", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Foriba.OE.CLIENT.serviceInvoicee.ProcessingFault), Action="getUBLList", Name="ProcessingFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Foriba.OE.CLIENT.serviceInvoicee.getUBLListResponse getUBLList(Foriba.OE.CLIENT.serviceInvoicee.getUBLListRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getUBLList", ReplyAction="*")]
        System.Threading.Tasks.Task<Foriba.OE.CLIENT.serviceInvoicee.getUBLListResponse> getUBLListAsync(Foriba.OE.CLIENT.serviceInvoicee.getUBLListRequest1 request);
        
        // CODEGEN: Generating message contract since the operation getUBL is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="getUBL", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Foriba.OE.CLIENT.serviceInvoicee.ProcessingFault), Action="getUBL", Name="ProcessingFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Foriba.OE.CLIENT.serviceInvoicee.getUBLResponse getUBL(Foriba.OE.CLIENT.serviceInvoicee.getUBLRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getUBL", ReplyAction="*")]
        System.Threading.Tasks.Task<Foriba.OE.CLIENT.serviceInvoicee.getUBLResponse> getUBLAsync(Foriba.OE.CLIENT.serviceInvoicee.getUBLRequest1 request);
        
        // CODEGEN: Generating message contract since the operation getEnvelopeStatus is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="getEnvelopeStatus", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Foriba.OE.CLIENT.serviceInvoicee.ProcessingFault), Action="getEnvelopeStatus", Name="ProcessingFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Foriba.OE.CLIENT.serviceInvoicee.getEnvelopeStatusResponse getEnvelopeStatus(Foriba.OE.CLIENT.serviceInvoicee.getEnvelopeStatusRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getEnvelopeStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<Foriba.OE.CLIENT.serviceInvoicee.getEnvelopeStatusResponse> getEnvelopeStatusAsync(Foriba.OE.CLIENT.serviceInvoicee.getEnvelopeStatusRequest1 request);
        
        // CODEGEN: Generating message contract since the operation getInvoiceView is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="getInvoiceView", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Foriba.OE.CLIENT.serviceInvoicee.ProcessingFault), Action="getInvoiceView", Name="ProcessingFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Foriba.OE.CLIENT.serviceInvoicee.getInvoiceViewResponse1 getInvoiceView(Foriba.OE.CLIENT.serviceInvoicee.getInvoiceViewRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getInvoiceView", ReplyAction="*")]
        System.Threading.Tasks.Task<Foriba.OE.CLIENT.serviceInvoicee.getInvoiceViewResponse1> getInvoiceViewAsync(Foriba.OE.CLIENT.serviceInvoicee.getInvoiceViewRequest1 request);
        
        // CODEGEN: Generating message contract since the operation getUserList is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="getUserList", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Foriba.OE.CLIENT.serviceInvoicee.ProcessingFault), Action="getUserList", Name="ProcessingFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Foriba.OE.CLIENT.serviceInvoicee.getUserListResponse getUserList(Foriba.OE.CLIENT.serviceInvoicee.getUserListRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getUserList", ReplyAction="*")]
        System.Threading.Tasks.Task<Foriba.OE.CLIENT.serviceInvoicee.getUserListResponse> getUserListAsync(Foriba.OE.CLIENT.serviceInvoicee.getUserListRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http:/fitcons.com/eInvoice/")]
    public partial class sendUBLRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string vKN_TCKNField;
        
        private string senderIdentifierField;
        
        private string receiverIdentifierField;
        
        private string docTypeField;
        
        private string[] parametersField;
        
        private byte[] docDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string VKN_TCKN {
            get {
                return this.vKN_TCKNField;
            }
            set {
                this.vKN_TCKNField = value;
                this.RaisePropertyChanged("VKN_TCKN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SenderIdentifier {
            get {
                return this.senderIdentifierField;
            }
            set {
                this.senderIdentifierField = value;
                this.RaisePropertyChanged("SenderIdentifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ReceiverIdentifier {
            get {
                return this.receiverIdentifierField;
            }
            set {
                this.receiverIdentifierField = value;
                this.RaisePropertyChanged("ReceiverIdentifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DocType {
            get {
                return this.docTypeField;
            }
            set {
                this.docTypeField = value;
                this.RaisePropertyChanged("DocType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Parameters", Order=4)]
        public string[] Parameters {
            get {
                return this.parametersField;
            }
            set {
                this.parametersField = value;
                this.RaisePropertyChanged("Parameters");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=5)]
        public byte[] DocData {
            get {
                return this.docDataField;
            }
            set {
                this.docDataField = value;
                this.RaisePropertyChanged("DocData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendUBLRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http:/fitcons.com/eInvoice/", Order=0)]
        public Foriba.OE.CLIENT.serviceInvoicee.sendUBLRequest sendUBLRequest;
        
        public sendUBLRequest1() {
        }
        
        public sendUBLRequest1(Foriba.OE.CLIENT.serviceInvoicee.sendUBLRequest sendUBLRequest) {
            this.sendUBLRequest = sendUBLRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendUBLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendUBLResponse", Namespace="http:/fitcons.com/eInvoice/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Response", IsNullable=false)]
        public Foriba.OE.CLIENT.serviceInvoicee.SendUBLResponseType[] sendUBLResponse1;
        
        public sendUBLResponse() {
        }
        
        public sendUBLResponse(Foriba.OE.CLIENT.serviceInvoicee.SendUBLResponseType[] sendUBLResponse1) {
            this.sendUBLResponse1 = sendUBLResponse1;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http:/fitcons.com/eInvoice/")]
    public partial class getUBLListRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string identifierField;
        
        private string vKN_TCKNField;
        
        private string[] uUIDField;
        
        private string docTypeField;
        
        private string typeField;
        
        private string[] parametersField;
        
        private System.DateTime fromDateField;
        
        private bool fromDateFieldSpecified;
        
        private System.DateTime toDateField;
        
        private bool toDateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
                this.RaisePropertyChanged("Identifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string VKN_TCKN {
            get {
                return this.vKN_TCKNField;
            }
            set {
                this.vKN_TCKNField = value;
                this.RaisePropertyChanged("VKN_TCKN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("UUID", Order=2)]
        public string[] UUID {
            get {
                return this.uUIDField;
            }
            set {
                this.uUIDField = value;
                this.RaisePropertyChanged("UUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DocType {
            get {
                return this.docTypeField;
            }
            set {
                this.docTypeField = value;
                this.RaisePropertyChanged("DocType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Parameters", Order=5)]
        public string[] Parameters {
            get {
                return this.parametersField;
            }
            set {
                this.parametersField = value;
                this.RaisePropertyChanged("Parameters");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public System.DateTime FromDate {
            get {
                return this.fromDateField;
            }
            set {
                this.fromDateField = value;
                this.RaisePropertyChanged("FromDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FromDateSpecified {
            get {
                return this.fromDateFieldSpecified;
            }
            set {
                this.fromDateFieldSpecified = value;
                this.RaisePropertyChanged("FromDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public System.DateTime ToDate {
            get {
                return this.toDateField;
            }
            set {
                this.toDateField = value;
                this.RaisePropertyChanged("ToDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ToDateSpecified {
            get {
                return this.toDateFieldSpecified;
            }
            set {
                this.toDateFieldSpecified = value;
                this.RaisePropertyChanged("ToDateSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http:/fitcons.com/eInvoice/")]
    public partial class GetUBLListResponseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string uUIDField;
        
        private string identifierField;
        
        private string vKN_TCKNField;
        
        private string envTypeField;
        
        private object envUUIDField;
        
        private string idField;
        
        private string custInvIDField;
        
        private System.DateTime insertDateTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UUID {
            get {
                return this.uUIDField;
            }
            set {
                this.uUIDField = value;
                this.RaisePropertyChanged("UUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
                this.RaisePropertyChanged("Identifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string VKN_TCKN {
            get {
                return this.vKN_TCKNField;
            }
            set {
                this.vKN_TCKNField = value;
                this.RaisePropertyChanged("VKN_TCKN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string EnvType {
            get {
                return this.envTypeField;
            }
            set {
                this.envTypeField = value;
                this.RaisePropertyChanged("EnvType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public object EnvUUID {
            get {
                return this.envUUIDField;
            }
            set {
                this.envUUIDField = value;
                this.RaisePropertyChanged("EnvUUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string CustInvID {
            get {
                return this.custInvIDField;
            }
            set {
                this.custInvIDField = value;
                this.RaisePropertyChanged("CustInvID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public System.DateTime InsertDateTime {
            get {
                return this.insertDateTimeField;
            }
            set {
                this.insertDateTimeField = value;
                this.RaisePropertyChanged("InsertDateTime");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUBLListRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http:/fitcons.com/eInvoice/", Order=0)]
        public Foriba.OE.CLIENT.serviceInvoicee.getUBLListRequest getUBLListRequest;
        
        public getUBLListRequest1() {
        }
        
        public getUBLListRequest1(Foriba.OE.CLIENT.serviceInvoicee.getUBLListRequest getUBLListRequest) {
            this.getUBLListRequest = getUBLListRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUBLListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUBLListResponse", Namespace="http:/fitcons.com/eInvoice/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("UBLList", IsNullable=false)]
        public Foriba.OE.CLIENT.serviceInvoicee.GetUBLListResponseType[] getUBLListResponse1;
        
        public getUBLListResponse() {
        }
        
        public getUBLListResponse(Foriba.OE.CLIENT.serviceInvoicee.GetUBLListResponseType[] getUBLListResponse1) {
            this.getUBLListResponse1 = getUBLListResponse1;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http:/fitcons.com/eInvoice/")]
    public partial class getUBLRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string identifierField;
        
        private string vKN_TCKNField;
        
        private string[] uUIDField;
        
        private string docTypeField;
        
        private string typeField;
        
        private string[] parametersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
                this.RaisePropertyChanged("Identifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string VKN_TCKN {
            get {
                return this.vKN_TCKNField;
            }
            set {
                this.vKN_TCKNField = value;
                this.RaisePropertyChanged("VKN_TCKN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("UUID", Order=2)]
        public string[] UUID {
            get {
                return this.uUIDField;
            }
            set {
                this.uUIDField = value;
                this.RaisePropertyChanged("UUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DocType {
            get {
                return this.docTypeField;
            }
            set {
                this.docTypeField = value;
                this.RaisePropertyChanged("DocType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Parameters", Order=5)]
        public string[] Parameters {
            get {
                return this.parametersField;
            }
            set {
                this.parametersField = value;
                this.RaisePropertyChanged("Parameters");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUBLRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http:/fitcons.com/eInvoice/", Order=0)]
        public Foriba.OE.CLIENT.serviceInvoicee.getUBLRequest getUBLRequest;
        
        public getUBLRequest1() {
        }
        
        public getUBLRequest1(Foriba.OE.CLIENT.serviceInvoicee.getUBLRequest getUBLRequest) {
            this.getUBLRequest = getUBLRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUBLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUBLResponse", Namespace="http:/fitcons.com/eInvoice/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("DocData", DataType="base64Binary", IsNullable=false)]
        public byte[][] getUBLResponse1;
        
        public getUBLResponse() {
        }
        
        public getUBLResponse(byte[][] getUBLResponse1) {
            this.getUBLResponse1 = getUBLResponse1;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http:/fitcons.com/eInvoice/")]
    public partial class getEnvelopeStatusRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string identifierField;
        
        private string vKN_TCKNField;
        
        private string[] uUIDField;
        
        private string[] parametersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
                this.RaisePropertyChanged("Identifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string VKN_TCKN {
            get {
                return this.vKN_TCKNField;
            }
            set {
                this.vKN_TCKNField = value;
                this.RaisePropertyChanged("VKN_TCKN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("UUID", Order=2)]
        public string[] UUID {
            get {
                return this.uUIDField;
            }
            set {
                this.uUIDField = value;
                this.RaisePropertyChanged("UUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Parameters", Order=3)]
        public string[] Parameters {
            get {
                return this.parametersField;
            }
            set {
                this.parametersField = value;
                this.RaisePropertyChanged("Parameters");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http:/fitcons.com/eInvoice/")]
    public partial class getEnvelopeStatusResponseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string uUIDField;
        
        private System.DateTime issueDateField;
        
        private string documentTypeCodeField;
        
        private string documentTypeField;
        
        private string responseCodeField;
        
        private string descriptionField;
        
        private byte[] docDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UUID {
            get {
                return this.uUIDField;
            }
            set {
                this.uUIDField = value;
                this.RaisePropertyChanged("UUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=1)]
        public System.DateTime IssueDate {
            get {
                return this.issueDateField;
            }
            set {
                this.issueDateField = value;
                this.RaisePropertyChanged("IssueDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string DocumentTypeCode {
            get {
                return this.documentTypeCodeField;
            }
            set {
                this.documentTypeCodeField = value;
                this.RaisePropertyChanged("DocumentTypeCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DocumentType {
            get {
                return this.documentTypeField;
            }
            set {
                this.documentTypeField = value;
                this.RaisePropertyChanged("DocumentType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ResponseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
                this.RaisePropertyChanged("ResponseCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=6)]
        public byte[] DocData {
            get {
                return this.docDataField;
            }
            set {
                this.docDataField = value;
                this.RaisePropertyChanged("DocData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getEnvelopeStatusRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http:/fitcons.com/eInvoice/", Order=0)]
        public Foriba.OE.CLIENT.serviceInvoicee.getEnvelopeStatusRequest getEnvelopeStatusRequest;
        
        public getEnvelopeStatusRequest1() {
        }
        
        public getEnvelopeStatusRequest1(Foriba.OE.CLIENT.serviceInvoicee.getEnvelopeStatusRequest getEnvelopeStatusRequest) {
            this.getEnvelopeStatusRequest = getEnvelopeStatusRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getEnvelopeStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getEnvelopeStatusResponse", Namespace="http:/fitcons.com/eInvoice/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Response", IsNullable=false)]
        public Foriba.OE.CLIENT.serviceInvoicee.getEnvelopeStatusResponseType[] getEnvelopeStatusResponse1;
        
        public getEnvelopeStatusResponse() {
        }
        
        public getEnvelopeStatusResponse(Foriba.OE.CLIENT.serviceInvoicee.getEnvelopeStatusResponseType[] getEnvelopeStatusResponse1) {
            this.getEnvelopeStatusResponse1 = getEnvelopeStatusResponse1;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http:/fitcons.com/eInvoice/")]
    public partial class getInvoiceViewRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string uUIDField;
        
        private string custInvIDField;
        
        private string identifierField;
        
        private string vKN_TCKNField;
        
        private string typeField;
        
        private string docTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UUID {
            get {
                return this.uUIDField;
            }
            set {
                this.uUIDField = value;
                this.RaisePropertyChanged("UUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CustInvID {
            get {
                return this.custInvIDField;
            }
            set {
                this.custInvIDField = value;
                this.RaisePropertyChanged("CustInvID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
                this.RaisePropertyChanged("Identifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string VKN_TCKN {
            get {
                return this.vKN_TCKNField;
            }
            set {
                this.vKN_TCKNField = value;
                this.RaisePropertyChanged("VKN_TCKN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string DocType {
            get {
                return this.docTypeField;
            }
            set {
                this.docTypeField = value;
                this.RaisePropertyChanged("DocType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http:/fitcons.com/eInvoice/")]
    public partial class getInvoiceViewResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] docDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=0)]
        public byte[] DocData {
            get {
                return this.docDataField;
            }
            set {
                this.docDataField = value;
                this.RaisePropertyChanged("DocData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getInvoiceViewRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http:/fitcons.com/eInvoice/", Order=0)]
        public Foriba.OE.CLIENT.serviceInvoicee.getInvoiceViewRequest getInvoiceViewRequest;
        
        public getInvoiceViewRequest1() {
        }
        
        public getInvoiceViewRequest1(Foriba.OE.CLIENT.serviceInvoicee.getInvoiceViewRequest getInvoiceViewRequest) {
            this.getInvoiceViewRequest = getInvoiceViewRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getInvoiceViewResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http:/fitcons.com/eInvoice/", Order=0)]
        public Foriba.OE.CLIENT.serviceInvoicee.getInvoiceViewResponse getInvoiceViewResponse;
        
        public getInvoiceViewResponse1() {
        }
        
        public getInvoiceViewResponse1(Foriba.OE.CLIENT.serviceInvoicee.getInvoiceViewResponse getInvoiceViewResponse) {
            this.getInvoiceViewResponse = getInvoiceViewResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http:/fitcons.com/eInvoice/")]
    public partial class getUserListRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string identifierField;
        
        private string vKN_TCKNField;
        
        private string roleField;
        
        private System.DateTime registeredAfterField;
        
        private bool registeredAfterFieldSpecified;
        
        private string filter_VKN_TCKNField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
                this.RaisePropertyChanged("Identifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string VKN_TCKN {
            get {
                return this.vKN_TCKNField;
            }
            set {
                this.vKN_TCKNField = value;
                this.RaisePropertyChanged("VKN_TCKN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Role {
            get {
                return this.roleField;
            }
            set {
                this.roleField = value;
                this.RaisePropertyChanged("Role");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime RegisteredAfter {
            get {
                return this.registeredAfterField;
            }
            set {
                this.registeredAfterField = value;
                this.RaisePropertyChanged("RegisteredAfter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RegisteredAfterSpecified {
            get {
                return this.registeredAfterFieldSpecified;
            }
            set {
                this.registeredAfterFieldSpecified = value;
                this.RaisePropertyChanged("RegisteredAfterSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Filter_VKN_TCKN {
            get {
                return this.filter_VKN_TCKNField;
            }
            set {
                this.filter_VKN_TCKNField = value;
                this.RaisePropertyChanged("Filter_VKN_TCKN");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http:/fitcons.com/eInvoice/")]
    public partial class UserType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string identifierField;
        
        private string aliasField;
        
        private string titleField;
        
        private string typeField;
        
        private System.DateTime registerTimeField;
        
        private System.DateTime firstCreationTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
                this.RaisePropertyChanged("Identifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Alias {
            get {
                return this.aliasField;
            }
            set {
                this.aliasField = value;
                this.RaisePropertyChanged("Alias");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("Title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime RegisterTime {
            get {
                return this.registerTimeField;
            }
            set {
                this.registerTimeField = value;
                this.RaisePropertyChanged("RegisterTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public System.DateTime FirstCreationTime {
            get {
                return this.firstCreationTimeField;
            }
            set {
                this.firstCreationTimeField = value;
                this.RaisePropertyChanged("FirstCreationTime");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUserListRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http:/fitcons.com/eInvoice/", Order=0)]
        public Foriba.OE.CLIENT.serviceInvoicee.getUserListRequest getUserListRequest;
        
        public getUserListRequest1() {
        }
        
        public getUserListRequest1(Foriba.OE.CLIENT.serviceInvoicee.getUserListRequest getUserListRequest) {
            this.getUserListRequest = getUserListRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUserListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUserListResponse", Namespace="http:/fitcons.com/eInvoice/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("User", IsNullable=false)]
        public Foriba.OE.CLIENT.serviceInvoicee.UserType[] getUserListResponse1;
        
        public getUserListResponse() {
        }
        
        public getUserListResponse(Foriba.OE.CLIENT.serviceInvoicee.UserType[] getUserListResponse1) {
            this.getUserListResponse1 = getUserListResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ClientEInvoiceServicesPortChannel : Foriba.OE.CLIENT.serviceInvoicee.ClientEInvoiceServicesPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClientEInvoiceServicesPortClient : System.ServiceModel.ClientBase<Foriba.OE.CLIENT.serviceInvoicee.ClientEInvoiceServicesPort>, Foriba.OE.CLIENT.serviceInvoicee.ClientEInvoiceServicesPort {
        
        public ClientEInvoiceServicesPortClient() {
        }
        
        public ClientEInvoiceServicesPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClientEInvoiceServicesPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientEInvoiceServicesPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientEInvoiceServicesPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Foriba.OE.CLIENT.serviceInvoicee.sendUBLResponse Foriba.OE.CLIENT.serviceInvoicee.ClientEInvoiceServicesPort.sendUBL(Foriba.OE.CLIENT.serviceInvoicee.sendUBLRequest1 request) {
            return base.Channel.sendUBL(request);
        }
        
        public Foriba.OE.CLIENT.serviceInvoicee.SendUBLResponseType[] sendUBL(Foriba.OE.CLIENT.serviceInvoicee.sendUBLRequest sendUBLRequest) {
            Foriba.OE.CLIENT.serviceInvoicee.sendUBLRequest1 inValue = new Foriba.OE.CLIENT.serviceInvoicee.sendUBLRequest1();
            inValue.sendUBLRequest = sendUBLRequest;
            Foriba.OE.CLIENT.serviceInvoicee.sendUBLResponse retVal = ((Foriba.OE.CLIENT.serviceInvoicee.ClientEInvoiceServicesPort)(this)).sendUBL(inValue);
            return retVal.sendUBLResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Foriba.OE.CLIENT.serviceInvoicee.sendUBLResponse> Foriba.OE.CLIENT.serviceInvoicee.ClientEInvoiceServicesPort.sendUBLAsync(Foriba.OE.CLIENT.serviceInvoicee.sendUBLRequest1 request) {
            return base.Channel.sendUBLAsync(request);
        }
        
        public System.Threading.Tasks.Task<Foriba.OE.CLIENT.serviceInvoicee.sendUBLResponse> sendUBLAsync(Foriba.OE.CLIENT.serviceInvoicee.sendUBLRequest sendUBLRequest) {
            Foriba.OE.CLIENT.serviceInvoicee.sendUBLRequest1 inValue = new Foriba.OE.CLIENT.serviceInvoicee.sendUBLRequest1();
            inValue.sendUBLRequest = sendUBLRequest;
            return ((Foriba.OE.CLIENT.serviceInvoicee.ClientEInvoiceServicesPort)(this)).sendUBLAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Foriba.OE.CLIENT.serviceInvoicee.getUBLListResponse Foriba.OE.CLIENT.serviceInvoicee.ClientEInvoiceServicesPort.getUBLList(Foriba.OE.CLIENT.serviceInvoicee.getUBLListRequest1 request) {
            return base.Channel.getUBLList(request);
        }
        
        public Foriba.OE.CLIENT.serviceInvoicee.GetUBLListResponseType[] getUBLList(Foriba.OE.CLIENT.serviceInvoicee.getUBLListRequest getUBLListRequest) {
            Foriba.OE.CLIENT.serviceInvoicee.getUBLListRequest1 inValue = new Foriba.OE.CLIENT.serviceInvoicee.getUBLListRequest1();
            inValue.getUBLListRequest = getUBLListRequest;
            Foriba.OE.CLIENT.serviceInvoicee.getUBLListResponse retVal = ((Foriba.OE.CLIENT.serviceInvoicee.ClientEInvoiceServicesPort)(this)).getUBLList(inValue);
            return retVal.getUBLListResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Foriba.OE.CLIENT.serviceInvoicee.getUBLListResponse> Foriba.OE.CLIENT.serviceInvoicee.ClientEInvoiceServicesPort.getUBLListAsync(Foriba.OE.CLIENT.serviceInvoicee.getUBLListRequest1 request) {
            return base.Channel.getUBLListAsync(request);
        }
        
        public System.Threading.Tasks.Task<Foriba.OE.CLIENT.serviceInvoicee.getUBLListResponse> getUBLListAsync(Foriba.OE.CLIENT.serviceInvoicee.getUBLListRequest getUBLListRequest) {
            Foriba.OE.CLIENT.serviceInvoicee.getUBLListRequest1 inValue = new Foriba.OE.CLIENT.serviceInvoicee.getUBLListRequest1();
            inValue.getUBLListRequest = getUBLListRequest;
            return ((Foriba.OE.CLIENT.serviceInvoicee.ClientEInvoiceServicesPort)(this)).getUBLListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Foriba.OE.CLIENT.serviceInvoicee.getUBLResponse Foriba.OE.CLIENT.serviceInvoicee.ClientEInvoiceServicesPort.getUBL(Foriba.OE.CLIENT.serviceInvoicee.getUBLRequest1 request) {
            return base.Channel.getUBL(request);
        }
        
        public byte[][] getUBL(Foriba.OE.CLIENT.serviceInvoicee.getUBLRequest getUBLRequest) {
            Foriba.OE.CLIENT.serviceInvoicee.getUBLRequest1 inValue = new Foriba.OE.CLIENT.serviceInvoicee.getUBLRequest1();
            inValue.getUBLRequest = getUBLRequest;
            Foriba.OE.CLIENT.serviceInvoicee.getUBLResponse retVal = ((Foriba.OE.CLIENT.serviceInvoicee.ClientEInvoiceServicesPort)(this)).getUBL(inValue);
            return retVal.getUBLResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Foriba.OE.CLIENT.serviceInvoicee.getUBLResponse> Foriba.OE.CLIENT.serviceInvoicee.ClientEInvoiceServicesPort.getUBLAsync(Foriba.OE.CLIENT.serviceInvoicee.getUBLRequest1 request) {
            return base.Channel.getUBLAsync(request);
        }
        
        public System.Threading.Tasks.Task<Foriba.OE.CLIENT.serviceInvoicee.getUBLResponse> getUBLAsync(Foriba.OE.CLIENT.serviceInvoicee.getUBLRequest getUBLRequest) {
            Foriba.OE.CLIENT.serviceInvoicee.getUBLRequest1 inValue = new Foriba.OE.CLIENT.serviceInvoicee.getUBLRequest1();
            inValue.getUBLRequest = getUBLRequest;
            return ((Foriba.OE.CLIENT.serviceInvoicee.ClientEInvoiceServicesPort)(this)).getUBLAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Foriba.OE.CLIENT.serviceInvoicee.getEnvelopeStatusResponse Foriba.OE.CLIENT.serviceInvoicee.ClientEInvoiceServicesPort.getEnvelopeStatus(Foriba.OE.CLIENT.serviceInvoicee.getEnvelopeStatusRequest1 request) {
            return base.Channel.getEnvelopeStatus(request);
        }
        
        public Foriba.OE.CLIENT.serviceInvoicee.getEnvelopeStatusResponseType[] getEnvelopeStatus(Foriba.OE.CLIENT.serviceInvoicee.getEnvelopeStatusRequest getEnvelopeStatusRequest) {
            Foriba.OE.CLIENT.serviceInvoicee.getEnvelopeStatusRequest1 inValue = new Foriba.OE.CLIENT.serviceInvoicee.getEnvelopeStatusRequest1();
            inValue.getEnvelopeStatusRequest = getEnvelopeStatusRequest;
            Foriba.OE.CLIENT.serviceInvoicee.getEnvelopeStatusResponse retVal = ((Foriba.OE.CLIENT.serviceInvoicee.ClientEInvoiceServicesPort)(this)).getEnvelopeStatus(inValue);
            return retVal.getEnvelopeStatusResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Foriba.OE.CLIENT.serviceInvoicee.getEnvelopeStatusResponse> Foriba.OE.CLIENT.serviceInvoicee.ClientEInvoiceServicesPort.getEnvelopeStatusAsync(Foriba.OE.CLIENT.serviceInvoicee.getEnvelopeStatusRequest1 request) {
            return base.Channel.getEnvelopeStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<Foriba.OE.CLIENT.serviceInvoicee.getEnvelopeStatusResponse> getEnvelopeStatusAsync(Foriba.OE.CLIENT.serviceInvoicee.getEnvelopeStatusRequest getEnvelopeStatusRequest) {
            Foriba.OE.CLIENT.serviceInvoicee.getEnvelopeStatusRequest1 inValue = new Foriba.OE.CLIENT.serviceInvoicee.getEnvelopeStatusRequest1();
            inValue.getEnvelopeStatusRequest = getEnvelopeStatusRequest;
            return ((Foriba.OE.CLIENT.serviceInvoicee.ClientEInvoiceServicesPort)(this)).getEnvelopeStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Foriba.OE.CLIENT.serviceInvoicee.getInvoiceViewResponse1 Foriba.OE.CLIENT.serviceInvoicee.ClientEInvoiceServicesPort.getInvoiceView(Foriba.OE.CLIENT.serviceInvoicee.getInvoiceViewRequest1 request) {
            return base.Channel.getInvoiceView(request);
        }
        
        public Foriba.OE.CLIENT.serviceInvoicee.getInvoiceViewResponse getInvoiceView(Foriba.OE.CLIENT.serviceInvoicee.getInvoiceViewRequest getInvoiceViewRequest) {
            Foriba.OE.CLIENT.serviceInvoicee.getInvoiceViewRequest1 inValue = new Foriba.OE.CLIENT.serviceInvoicee.getInvoiceViewRequest1();
            inValue.getInvoiceViewRequest = getInvoiceViewRequest;
            Foriba.OE.CLIENT.serviceInvoicee.getInvoiceViewResponse1 retVal = ((Foriba.OE.CLIENT.serviceInvoicee.ClientEInvoiceServicesPort)(this)).getInvoiceView(inValue);
            return retVal.getInvoiceViewResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Foriba.OE.CLIENT.serviceInvoicee.getInvoiceViewResponse1> Foriba.OE.CLIENT.serviceInvoicee.ClientEInvoiceServicesPort.getInvoiceViewAsync(Foriba.OE.CLIENT.serviceInvoicee.getInvoiceViewRequest1 request) {
            return base.Channel.getInvoiceViewAsync(request);
        }
        
        public System.Threading.Tasks.Task<Foriba.OE.CLIENT.serviceInvoicee.getInvoiceViewResponse1> getInvoiceViewAsync(Foriba.OE.CLIENT.serviceInvoicee.getInvoiceViewRequest getInvoiceViewRequest) {
            Foriba.OE.CLIENT.serviceInvoicee.getInvoiceViewRequest1 inValue = new Foriba.OE.CLIENT.serviceInvoicee.getInvoiceViewRequest1();
            inValue.getInvoiceViewRequest = getInvoiceViewRequest;
            return ((Foriba.OE.CLIENT.serviceInvoicee.ClientEInvoiceServicesPort)(this)).getInvoiceViewAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Foriba.OE.CLIENT.serviceInvoicee.getUserListResponse Foriba.OE.CLIENT.serviceInvoicee.ClientEInvoiceServicesPort.getUserList(Foriba.OE.CLIENT.serviceInvoicee.getUserListRequest1 request) {
            return base.Channel.getUserList(request);
        }
        
        public Foriba.OE.CLIENT.serviceInvoicee.UserType[] getUserList(Foriba.OE.CLIENT.serviceInvoicee.getUserListRequest getUserListRequest) {
            Foriba.OE.CLIENT.serviceInvoicee.getUserListRequest1 inValue = new Foriba.OE.CLIENT.serviceInvoicee.getUserListRequest1();
            inValue.getUserListRequest = getUserListRequest;
            Foriba.OE.CLIENT.serviceInvoicee.getUserListResponse retVal = ((Foriba.OE.CLIENT.serviceInvoicee.ClientEInvoiceServicesPort)(this)).getUserList(inValue);
            return retVal.getUserListResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Foriba.OE.CLIENT.serviceInvoicee.getUserListResponse> Foriba.OE.CLIENT.serviceInvoicee.ClientEInvoiceServicesPort.getUserListAsync(Foriba.OE.CLIENT.serviceInvoicee.getUserListRequest1 request) {
            return base.Channel.getUserListAsync(request);
        }
        
        public System.Threading.Tasks.Task<Foriba.OE.CLIENT.serviceInvoicee.getUserListResponse> getUserListAsync(Foriba.OE.CLIENT.serviceInvoicee.getUserListRequest getUserListRequest) {
            Foriba.OE.CLIENT.serviceInvoicee.getUserListRequest1 inValue = new Foriba.OE.CLIENT.serviceInvoicee.getUserListRequest1();
            inValue.getUserListRequest = getUserListRequest;
            return ((Foriba.OE.CLIENT.serviceInvoicee.ClientEInvoiceServicesPort)(this)).getUserListAsync(inValue);
        }
    }
}
